### ISSUE TITLE
Google map location (Feature Request)

### ISSUE THREAD

**Issue by CaptainAchilles** [MrCeleryman/ParmyayWeb#15]
We could use something like [vue2-google](https://www.npmjs.com/package/vue2-google-maps) to easily add google maps to the Venue pages?

**some discussion on where this fits into the overall project / MVP**

**Comment by CaptainAchilles** [comment]
Implemented an initial go at this on branch feature-map-#15
It needs some tidying up to work with a typescript setup.

**Comment by MrCeleryman** [comment]
Thanks @CaptainAchilles I will have a look 👍

**Comment by MrCeleryman** [comment]
Hey @CaptainAchilles I added an API key as well as fixing some linting configuration and errors 💃

**Comment by CaptainAchilles** [comment]
Thanks for that, Dan! 📖 
I am having a bit of trouble separating out the `Vue.use` and `Vue.filter` items nicely. I feel like they are polluting the app entry, and am not sure of a neat and intuitive way to abstract them away.
https://github.com/MrCeleryman/ParmyayWeb/blob/79a49300090b1df5f09f4f232f081e63388cba4e/src/main.ts#L12

The best I can think of is something like 
`import VueSetup from "vueSetup"` which runs the `Vue.use` and`Vue.filter` code in the background.

What are you thoughts on this?

**Comment by MrCeleryman** [comment]
Hi @CaptainAchilles I think that is a good idea as we may get more plugins in future and could make the entry point quite bloated.

I think the best way to go about this is creating a config folder under src and putting a `plugins.ts` file there that loads all the plugins and filter.

I also had a look at your recent changes and fixed up some links but also decided to do some restructuring of the components folder as I saw you doing some restructuring of the other files.

I have created a folder structure under `src/components` as such:
```
src
├── components
├── routes
├── utils
└── routes
```

**Comment by CaptainAchilles** [comment]
Hey @MrCeleryman,
I like the idea of better organizing the components, but I feel like organisation by frequency of use is a bad pattern.

I think organizing based on category is more appropriate:
```
components
├── views      # different page views (venue, error, main etc.)
├── charts     # for charts
└── misc       # for components like rating, triSwitch. Could probably be better named.
```

This structure has the advantage that it is easier to locate things by intention, and the root folders are generic enough to contain more specific subfolders.

**Comment by MrCeleryman** [comment]
I don't think its grouping by frequency of use but by grouping by components that are related.

So you could further break down the commonly used components into charts and other catergories and giving each "view" it's own folder which contains all of the pages and components that are used in creating that view. Thoughts?

Also added the settings json from Parmyay to this repo too 🙌
