### ISSUE TITLE
getBoundingClientRect of Triswitch not getting the expected values

### ISSUE THREAD

**Issue by MrCeleryman** [MrCeleryman/ParmyayWeb#22]
```
let dimensions = (this.$el.parentNode as HTMLElement)
				.getBoundingClientRect();
```

Line 101 triswitch.vue

As discussed with @CaptainAchilles

**Comment by CaptainAchilles** [comment]
It seems that dimensions does not correspond to the width and height of the parentNode, since the parent node is being set to 200px width and height.

**Comment by CaptainAchilles** [comment]
It looks like when calling `$mount("app")` it is actually replacing the `app` container. It looks like it can be fixed by appending a child and mounting onto that.

**Comment by CaptainAchilles** [comment]
It works; I'll open  PR shortly

**Comment by MrCeleryman** [comment]
awesome 🎉
