### ISSUE TITLE
Shims for es compatibiliy

### ISSUE THREAD

**Issue by CaptainAchilles** [MrCeleryman/ParmyayWeb#3]
Duplicate of https://github.com/MrCeleryman/Parmyay/issues/39

Our project is targeting es6, however we have no shims in place for older browsers. I think it is appropriate to use something like the following to preserve backwards compatibility for our application.

Using babel-polyfill for now

**Comment by MrCeleryman** [comment]
Whats the progress on this @CaptainAchilles ?

**Comment by CaptainAchilles** [comment]
Closed in #14
