### ISSUE TITLE
Unit Testing Setup

### ISSUE THREAD

**Issue by MrCeleryman** [MrCeleryman/ParmyayWeb#5]
@CaptainAchilles  mentioned in the Parmyay [issue](https://github.com/MrCeleryman/Parmyay/issues/21)
https://github.com/CaptainAchilles/vue-typescript-webpack

**Comment by CaptainAchilles** [comment]
Unit testing was merged in with #2.

See `npm run unit`

**Comment by CaptainAchilles** [comment]
I'll do a PR to document this
